services:
  dev-http: &dev
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    env_file: docker.env
    environment:
      APP_NAME: "backend-fastapi"
      PYTHONPATH: "/app/src"
    ports:
      - '8000:8000'
    working_dir: "/app/src"
    volumes:
      - '.:/app'
    depends_on:
      otel-collector:
        condition: service_started
    command:
      - python
      - ./http_app/dev_server.py

  #########################
  #### Helper services ####
  #########################

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14268:14268" # HTTP port for spans

  otel-collector:
    image: grafana/alloy:latest
    # You can add the Grafana Cloud credentials in this file
    # and push observability directly to the provider.
    # Refer to the config.alloy file to see what credentials we need.
    env_file:
      - path: ./docker.env
      - path: ./credentials.env
        required: false
    depends_on:
      - jaeger
    ports:
      - "12345:12345"
      - "4317:4317"
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=experimental
#      - --stability.level=public-preview
      - /etc/alloy/config.alloy

  ##########################
  #### One-off commands ####
  ##########################
  test:
    <<: *dev
    environment:
      APP_NAME: "backend-test"
    working_dir: "/app"
    ports: []
    command:
      - "make"
      - "test"
